# Match Kitti Sequence version 22-11

Reads a sequence of stereo images as Frame. The Frames are scanned to identify FramePoints that are pixels that are at the top or botrom of vertical lines in the image. A patch is taken around each of the FramePoints in the left hand image, to match these to a patch in the right hand image and estimate the disparity/distance of the framePoint.

A Sequence is created in which the first Frame is the KeyFrame. It's initial FramePoints are culled to keep only the points for which there is a confident estimate of its depth. The consecutive frames are used to track the KeyFrame's remaining FramePoints. Only a limited number of all framePoints will be found in the consecutive frames, mostly because nearby objects become larger quickly as we get closer. The matching FramePoints are given the same FramePointId as the corresponding point in the KeyFrame and its depth is estimated.

The results are dumped into a folder 'dump', containing files 0.txt, 1.txt, etc. 0.txt contains the FramePoints as observed from the first frame, 1.txt form the second frame, etc. In these files, each row contains a single FramePoint with the values FramePointID, X, Y, Depth.

In [1]:
# when you change a setting you have to restart the kernel (settings are only loaded once)
import os
os.environ['STEREO_CONFIDENCE'] = '1.6'
os.environ['SEQUENCE_CONFIDENCE'] = '1.6'
#os.environ['PATCH_SIZE'] = '17'
FRAMECOUNT = 1101

from pyurb.urb_kitti import *
%matplotlib inline
import numpy as np

Read the first 10 frames from KITTI sequence 00.

In [2]:
%%time
LEFTDIR = '/data/urbinn/datasets/kitti/sequences/01/image_2'
RIGHTDIR = '/data/urbinn/datasets/kitti/sequences/01/image_3'

frame = []
for frameid in range(FRAMECOUNT):
    filename = '%06d.png'%(frameid)
    left_frame = Frame(LEFTDIR + '/' + filename, RIGHTDIR)
    frame.append(left_frame)

CPU times: user 389 µs, sys: 928 µs, total: 1.32 ms
Wall time: 1.32 ms


In [ ]:
%%bash
ls /data/urbinn/datasets/kitti/sequences/01/image_2 | wc -l


1101


Inspect the FramePoints for the first frame

We can also manually compute the Depth of the points and show these

Turn the list of frames into a sequence. The first frame is automatically taken as the KeyFrame and its FramePoints are rerieved, depth is estimated, only the most confident points are kept, and they are tracked in the other frames.

In [ ]:
seq = Sequence()
for f in ProgressBar()(frame):
    seq.add_frame(f)

  0% (5 of 1101) |                        | Elapsed Time: 0:00:06 ETA:  0:24:54

invalid speed 4.20373948795 -1.03510464781 
 [[ 0.97477079  0.0036529  -0.22317834  1.76321253]
 [-0.00251859  0.99998243  0.00536694 -0.1015843 ]
 [ 0.22319402 -0.00466944  0.97476286 -0.01759371]
 [ 0.          0.          0.          1.        ]]


  1% (16 of 1101) |                       | Elapsed Time: 0:00:18 ETA:  0:11:38

150 -1.00338851616 [[  9.98943459e-01   9.72309543e-05  -4.59560289e-02  -2.08941232e-02]
 [ -1.12544650e-05   9.99998249e-01   1.87109748e-03   7.17438652e-03]
 [  4.59561304e-02  -1.86860338e-03   9.98941711e-01  -1.00338852e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -2.08640786322 -1.09959396519 
 [[  9.95641204e-01   3.08054441e-03  -9.32153570e-02   6.39715736e-02]
 [ -2.89525640e-03   9.99993555e-01   2.12291185e-03   3.22341005e-02]
 [  9.32212960e-02  -1.84377615e-03   9.95643707e-01  -2.08640786e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  1% (17 of 1101) |                       | Elapsed Time: 0:00:21 ETA:  0:14:50

146 -1.00517670237 [[  9.98912562e-01   3.57953037e-03  -4.64852676e-02  -1.64516709e-02]
 [ -3.59418415e-03   9.99993514e-01  -2.31654796e-04   3.21980523e-02]
 [  4.64841369e-02   3.98479497e-04   9.98918949e-01  -1.00517670e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -2.04236292523 -1.06812154425 
 [[  9.95616080e-01   3.06044939e-03  -9.34839845e-02   8.86356017e-02]
 [ -2.99482780e-03   9.99995161e-01   8.42239115e-04   3.24173737e-02]
 [  9.34861098e-02  -5.58578370e-04   9.95620427e-01  -2.04236293e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  2% (29 of 1101) |                       | Elapsed Time: 0:00:31 ETA:  0:13:34

invalid speed 0.00978176847203 -0.836114527871 
 [[  9.94458456e-01  -1.91204635e-03  -1.05112909e-01   1.16544995e-01]
 [  1.18729390e-03   9.99975094e-01  -6.95713093e-03   2.61644327e-01]
 [  1.05123593e-01   6.79377777e-03   9.94435958e-01  -1.36437807e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  2% (32 of 1101) |                       | Elapsed Time: 0:00:36 ETA:  0:20:18

invalid speed 1.6025639317 -1.05312674112 
 [[ 0.98815847 -0.01312812 -0.15287411  1.97624828]
 [ 0.01701677  0.99956336  0.02415632 -2.46549206]
 [ 0.15249023 -0.0264717   0.98795039 -1.74563854]
 [ 0.          0.          0.          1.        ]]


  3% (35 of 1101) |                       | Elapsed Time: 0:00:44 ETA:  0:29:24

invalid speed -2.60391667444 -1.08572143743 
 [[ 0.98866279  0.04793615 -0.14229549  2.92971594]
 [-0.04469653  0.99866537  0.02587838 -1.77550021]
 [ 0.14334609 -0.01922487  0.98948588 -5.90480226]
 [ 0.          0.          0.          1.        ]]


  3% (39 of 1101) |                       | Elapsed Time: 0:00:59 ETA:  0:48:52

invalid speed 1.04788572238 -1.14306766881 
 [[ 0.98621678 -0.0109049  -0.16509858  3.48114586]
 [ 0.01397536  0.99975011  0.01744753 -1.9040428 ]
 [ 0.16486706 -0.01951436  0.98612273 -3.57027774]
 [ 0.          0.          0.          1.        ]]


  4% (46 of 1101) |                       | Elapsed Time: 0:01:26 ETA:  0:58:39

invalid speed 49.6375225953 -1.05211915808 
 [[  9.77455870e-01   9.97685144e-03  -2.10903969e-01   1.99213376e+01]
 [ -9.87686215e-03   9.99950056e-01   1.52750217e-03  -5.52421497e+00]
 [  2.10908675e-01   5.90003469e-04   9.77505592e-01   4.17137463e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  4% (49 of 1101) |#                      | Elapsed Time: 0:01:50 ETA:  1:29:25

invalid speed 4.40441479961 -1.23627740149 
 [[ 0.99888723  0.01217285 -0.04556454  2.50112023]
 [-0.01201411  0.99992077  0.00375614  0.13688259]
 [ 0.04560665 -0.00320454  0.99895434  0.55834975]
 [ 0.          0.          0.          1.        ]]


  4% (52 of 1101) |#                      | Elapsed Time: 0:02:19 ETA:  1:52:23

invalid speed 4.45539006632 -1.33682050348 
 [[  9.99100797e-01   1.46041332e-02  -3.98034864e-02   3.16815026e+00]
 [ -1.47382846e-02   9.99886645e-01  -3.07897970e-03   5.28286593e-01]
 [  3.97540086e-02   3.66284618e-03   9.99202783e-01   3.60216947e-01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  4% (55 of 1101) |#                      | Elapsed Time: 0:02:50 ETA:  2:32:16

invalid speed 0.478050825004 -1.39480571998 
 [[  9.99851794e-01   4.76945610e-04  -1.72093556e-02   8.36729146e-01]
 [ -5.41967726e-04   9.99992732e-01  -3.77383448e-03  -7.76344504e-02]
 [  1.72074306e-02   3.78260209e-03   9.99844786e-01  -3.77852074e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  5% (57 of 1101) |#                      | Elapsed Time: 0:03:15 ETA:  2:43:25

invalid speed -2.37117636669 -1.13749648632 
 [[  9.99984670e-01   2.21017224e-03  -5.07698858e-03  -1.43950854e-02]
 [ -2.21638286e-03   9.99996802e-01  -1.21798884e-03   4.40001494e-02]
 [  5.07428038e-03   1.22922272e-03   9.99986370e-01  -4.40907461e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  5% (59 of 1101) |#                      | Elapsed Time: 0:03:39 ETA:  3:09:25

invalid speed 0.87942504761 -1.32365502873 
 [[  9.99955515e-01  -1.37953531e-04  -9.43128771e-03   1.05711580e+00]
 [  1.47466546e-04   9.99999481e-01   1.00797755e-03  -2.50675353e-01]
 [  9.43114377e-03  -1.00932351e-03   9.99955016e-01  -2.06290328e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  5% (62 of 1101) |#                      | Elapsed Time: 0:04:04 ETA:  3:02:05

invalid speed -3.31129368999 -0.995690109639 
 [[  9.99997561e-01  -1.10310887e-03   1.91337610e-03   7.25080781e-02]
 [  1.10426913e-03   9.99999207e-01  -6.05444787e-04   1.12333900e-01]
 [ -1.91270671e-03   6.07556192e-04   9.99997986e-01  -6.43867452e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  5% (65 of 1101) |#                      | Elapsed Time: 0:04:29 ETA:  2:50:23

invalid speed 1.91928953102 -1.00145842663 
 [[  9.99822125e-01  -9.59480200e-03  -1.62375559e-02   2.63826542e+00]
 [  9.60993891e-03   9.99953458e-01   8.54444770e-04  -5.13070123e-01]
 [  1.62286020e-02  -1.01033471e-03   9.99867797e-01  -1.61434353e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  6% (67 of 1101) |#                      | Elapsed Time: 0:04:49 ETA:  2:42:25

invalid speed -2.45801638068 -0.978547943441 
 [[ 0.99977077  0.02089468  0.00467146  0.04622987]
 [-0.02085166  0.99974139 -0.00907546  0.71357378]
 [-0.00485988  0.00897597  0.99994791 -4.60125563]
 [ 0.          0.          0.          1.        ]]


  6% (71 of 1101) |#                      | Elapsed Time: 0:05:16 ETA:  2:10:16

invalid speed -2.05050430269 -1.60552457573 
 [[  9.99959313e-01   6.97060403e-03   5.72562064e-03  -2.60561144e-01]
 [ -6.94663804e-03   9.99967072e-01  -4.19502222e-03   2.99148675e-01]
 [ -5.75467395e-03   4.15507772e-03   9.99974809e-01  -9.02016583e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  7% (83 of 1101) |#                      | Elapsed Time: 0:06:35 ETA:  1:38:10

invalid speed -3.83388962452 -1.5487133082 
 [[  9.99821160e-01  -1.27373271e-02  -1.39788670e-02   8.80124579e-01]
 [  1.25986449e-02   9.99870983e-01  -9.96447500e-03   1.47434538e+00]
 [  1.41039842e-02   9.78657817e-03   9.99852639e-01  -1.14737790e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  7% (85 of 1101) |#                      | Elapsed Time: 0:06:52 ETA:  1:55:46

invalid speed 2.11978276046 -1.63558813354 
 [[ 0.9999346  -0.00195494 -0.01126835  0.15617986]
 [ 0.00192902  0.99999547 -0.00231044  0.00758575]
 [ 0.01127282  0.00228855  0.99993384 -1.36238102]
 [ 0.          0.          0.          1.        ]]


  7% (86 of 1101) |#                      | Elapsed Time: 0:07:09 ETA:  2:16:02

invalid speed -2.15681196107 -1.70815508085 
 [[  9.99956874e-01  -1.99063181e-03  -9.07120598e-03   5.19607986e-02]
 [  1.99085117e-03   9.99998018e-01   1.51515033e-05   2.04887425e-02]
 [  9.07115784e-03  -3.32102709e-05   9.99958856e-01  -4.01010094e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  8% (90 of 1101) |#                      | Elapsed Time: 0:07:50 ETA:  2:19:35

160 -2.0115143097 [[  9.99990113e-01   2.97515265e-04  -4.43678222e-03  -1.41071964e-02]
 [ -2.89930990e-04   9.99998496e-01   1.70995401e-03   8.25099768e-03]
 [  4.43728428e-03  -1.70865075e-03   9.99988695e-01  -2.01151431e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -4.0685340101 -1.86803180306 
 [[  9.99960237e-01  -7.26474782e-04  -8.88805136e-03  -2.46532614e-02]
 [  7.55451516e-04   9.99994410e-01   3.25726690e-03   2.45507834e-02]
 [  8.88563535e-03  -3.26385187e-03   9.99955195e-01  -4.06853401e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  8% (91 of 1101) |#                      | Elapsed Time: 0:08:04 ETA:  2:39:21

152 -2.02823761849 [[  9.99990109e-01  -4.64042535e-04  -4.42351350e-03  -1.00494449e-02]
 [  4.71201709e-04   9.99998581e-01   1.61753117e-03   2.04723614e-02]
 [  4.42275662e-03  -1.61959954e-03   9.99988908e-01  -2.02823762e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  8% (92 of 1101) |#                      | Elapsed Time: 0:08:07 ETA:  2:38:56

invalid speed -4.21696621408 -1.87169173173 
 [[  9.99877438e-01  -6.10170824e-03  -1.44179603e-02   2.81667946e-02]
 [  6.13315961e-03   9.99978906e-01   2.13819287e-03   1.60581049e-02]
 [  1.44046096e-02  -2.22635846e-03   9.99893770e-01  -5.98917393e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  8% (93 of 1101) |#                      | Elapsed Time: 0:08:20 ETA:  2:56:07

110 -2.05201274959 [[  9.99987969e-01  -1.36299312e-03  -4.71222071e-03  -1.18888374e-02]
 [  1.36464593e-03   9.99999008e-01   3.47552924e-04   6.15776248e-03]
 [  4.71174233e-03  -3.53979255e-04   9.99988837e-01  -2.05201275e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  8% (94 of 1101) |#                      | Elapsed Time: 0:08:22 ETA:  2:35:38

invalid speed -4.48075883829 -1.8775433348 
 [[  9.99860262e-01  -7.25772780e-03  -1.50592491e-02  -3.18977274e-02]
 [  7.24098866e-03   9.99973104e-01  -1.16578007e-03   6.76705727e-02]
 [  1.50673049e-02   1.05657332e-03   9.99885923e-01  -6.24979137e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  8% (96 of 1101) |##                     | Elapsed Time: 0:08:35 ETA:  2:24:00

invalid speed -2.78720351572 -1.53135431775 
 [[  9.99845734e-01   8.44659252e-04  -1.75441084e-02   3.39393052e-01]
 [ -8.33926378e-04   9.99999461e-01   6.19071982e-04   2.82295784e-02]
 [  1.75446218e-02  -6.04345985e-04   9.99845899e-01  -5.46468566e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  8% (97 of 1101) |##                     | Elapsed Time: 0:08:49 ETA:  2:19:43

198 -2.00985772398 [[  9.99865069e-01   7.82078791e-04  -1.64083225e-02   5.41580420e-01]
 [ -7.82640522e-04   9.99999693e-01  -2.78132143e-05   7.49193569e-02]
 [  1.64082957e-02   4.06512795e-05   9.99865374e-01  -2.00985772e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -4.19920206226 -1.69085545316 
 [[  9.99918510e-01  -3.09756875e-04  -1.27623633e-02   8.74968715e-02]
 [  3.40719701e-04   9.99997004e-01   2.42400161e-03   3.09004168e-02]
 [  1.27615742e-02  -2.42815247e-03   9.99915620e-01  -4.19920206e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  8% (98 of 1101) |##                     | Elapsed Time: 0:09:04 ETA:  2:37:27

173 -2.1392869871 [[  9.99969365e-01  -5.12817235e-04  -7.81069797e-03   8.68089219e-02]
 [  5.22282667e-04   9.99999132e-01   1.20986323e-03   1.35882582e-02]
 [  7.81007075e-03  -1.21390556e-03   9.99968764e-01  -2.13928699e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -3.52133929157 -1.84033263114 
 [[  9.99890483e-01  -1.73372760e-04  -1.47983456e-02   4.47224983e-01]
 [  1.86966498e-04   9.99999562e-01   9.17219939e-04   5.40365042e-04]
 [  1.47981801e-02  -9.19886283e-04   9.99890078e-01  -3.52133929e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  8% (99 of 1101) |##                     | Elapsed Time: 0:09:17 ETA:  2:51:45

invalid speed -2.42913910461 -1.81396053549 
 [[  9.99887580e-01  -1.07469029e-05  -1.49942587e-02   1.91945391e-01]
 [  1.64084064e-05   9.99999929e-01   3.77455114e-04   3.37196584e-02]
 [  1.49942536e-02  -3.77658712e-04   9.99887509e-01  -4.19035545e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  9% (100 of 1101) |#                     | Elapsed Time: 0:09:27 ETA:  2:41:51

205 -2.11154347647 [[  9.99982043e-01  -9.71855772e-04  -5.91354961e-03   2.46055643e-02]
 [  9.73647916e-04   9.99999481e-01   3.00186023e-04   1.11736517e-02]
 [  5.91325480e-03  -3.05938348e-04   9.99982470e-01  -2.11154348e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -4.196707748 -1.91315484915 
 [[  9.99941520e-01   9.83592865e-04  -1.07698378e-02   3.49283764e-02]
 [ -9.74143877e-04   9.99999136e-01   8.82567199e-04   7.69195730e-02]
 [  1.07706966e-02  -8.72024215e-04   9.99941614e-01  -4.19670775e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  9% (101 of 1101) |##                    | Elapsed Time: 0:09:36 ETA:  2:33:19

122 -2.10103613314 [[  9.99981515e-01   1.12757979e-04  -6.07914844e-03   4.58832283e-02]
 [ -1.07935294e-04   9.99999679e-01   7.93638068e-04   3.41317997e-02]
 [  6.07923598e-03  -7.92967244e-04   9.99981207e-01  -2.10103613e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  9% (102 of 1101) |##                    | Elapsed Time: 0:09:43 ETA:  2:40:08

96 -2.2339671983 [[  9.99956412e-01  -1.57050533e-03  -9.20371107e-03   1.35524776e-01]
 [  1.58131751e-03   9.99998068e-01   1.16760445e-03  -1.05903379e-02]
 [  9.20185956e-03  -1.18210755e-03   9.99956963e-01  -2.23396720e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  9% (103 of 1101) |##                    | Elapsed Time: 0:09:48 ETA:  2:27:05

15 -3.79945169012 [[  9.99996433e-01   2.60269219e-03  -5.99932823e-04  -8.73104897e-01]
 [ -2.60373119e-03   9.99995101e-01  -1.73763398e-03   3.07546821e-01]
 [  5.95407358e-04   1.73918984e-03   9.99998310e-01  -3.79945169e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  9% (104 of 1101) |##                    | Elapsed Time: 0:09:53 ETA:  2:32:13

10 -4.32995691984 [[ 0.99781584  0.01892143 -0.06328927  0.78155483]
 [-0.01986038  0.99970135 -0.0142397   0.6279439 ]
 [ 0.06300093  0.01546554  0.99789363 -4.32995692]
 [ 0.          0.          0.          1.        ]]


  9% (105 of 1101) |##                    | Elapsed Time: 0:09:59 ETA:  2:24:05

invalid speed -2.72875703387 -2.68050475497 
 [[  9.99974473e-01   3.40976107e-03  -6.27911054e-03   4.62258447e-02]
 [ -3.40317531e-03   9.99993648e-01   1.05922123e-03   4.29595136e-02]
 [  6.28268235e-03  -1.03782527e-03   9.99979725e-01  -4.36223821e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  9% (106 of 1101) |##                    | Elapsed Time: 0:10:10 ETA:  2:38:16

33 -2.08953956625 [[  9.99870765e-01   1.58747796e-02  -2.53852048e-03   6.81413591e-02]
 [ -1.58782635e-02   9.99873010e-01  -1.35818143e-03   2.66592168e-01]
 [  2.51663728e-03   1.39831321e-03   9.99995856e-01  -2.08953957e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -6.57395402113 -2.48351635873 
 [[  9.99933518e-01  -7.98215162e-03  -8.32134960e-03   2.31371936e-01]
 [  7.96223957e-03   9.99965365e-01  -2.42327740e-03   7.09614485e-01]
 [  8.34040436e-03   2.35685972e-03   9.99962441e-01  -6.57395402e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  9% (107 of 1101) |##                    | Elapsed Time: 0:10:21 ETA:  2:32:14

92 -2.19827966313 [[  9.99993217e-01  -9.28206998e-04  -3.56429811e-03   2.16130818e-02]
 [  9.27080684e-04   9.99999520e-01  -3.17637998e-04   2.49670994e-02]
 [  3.56459123e-03   3.14331452e-04   9.99993597e-01  -2.19827966e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -4.60093314263 -2.38843746019 
 [[  9.99956094e-01  -2.00839701e-03  -9.15297152e-03   1.89442118e-01]
 [  2.02392464e-03   9.99996528e-01   1.68751063e-03  -3.82565690e-02]
 [  9.14955055e-03  -1.70596147e-03   9.99956687e-01  -4.60093314e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  9% (108 of 1101) |##                    | Elapsed Time: 0:10:30 ETA:  2:22:25

291 -2.1927554604 [[  9.99991198e-01  -1.13456102e-03  -4.03937140e-03   1.42444403e-02]
 [  1.13831482e-03   9.99998922e-01   9.27126522e-04   1.28471393e-02]
 [  4.03831516e-03  -9.31716438e-04   9.99991412e-01  -2.19275546e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


  9% (109 of 1101) |##                    | Elapsed Time: 0:10:41 ETA:  2:19:06

35 -2.17960812818 [[  9.99989499e-01  -1.18925258e-03  -4.42567293e-03   2.07173150e-02]
 [  1.19300606e-03   9.99998931e-01   8.45570758e-04   2.54187477e-03]
 [  4.42466261e-03  -8.50841733e-04   9.99989849e-01  -2.17960813e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


 10% (111 of 1101) |##                    | Elapsed Time: 0:11:02 ETA:  2:22:34

27 -2.18335607746 [[  9.99983560e-01   2.65700402e-04  -5.72790421e-03   4.01430071e-02]
 [ -2.73609482e-04   9.99999010e-01  -1.38005882e-03   1.32881833e-01]
 [  5.72753186e-03   1.38160334e-03   9.99982643e-01  -2.18335608e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


 10% (112 of 1101) |##                    | Elapsed Time: 0:11:12 ETA:  2:26:59

16 54.210141361 [[  3.70478982e-01  -9.05867028e-01   2.05305266e-01  -4.65385187e+01]
 [  9.28112468e-01   3.52280468e-01  -1.20439686e-01   1.29166394e+01]
 [  3.67773052e-02   2.35166749e-01   9.71258992e-01   5.42101414e+01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


 10% (113 of 1101) |##                    | Elapsed Time: 0:11:21 ETA:  2:33:46

9 2.23591497292e-06 [[  9.99996342e-01  -1.34165634e-04  -2.70149022e-03  -1.19594381e-05]
 [  1.37814403e-04   9.99999079e-01   1.35050986e-03   6.09225136e-06]
 [  2.70130654e-03  -1.35087722e-03   9.99995439e-01   2.23591497e-06]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


 10% (114 of 1101) |##                    | Elapsed Time: 0:11:32 ETA:  2:42:13

148 -2.25151107107 [[  9.99989663e-01  -1.25235300e-04  -4.54518620e-03   3.98699982e-02]
 [  1.21131791e-04   9.99999585e-01  -9.03089313e-04   2.65989038e-02]
 [  4.54529742e-03   9.02529411e-04   9.99989263e-01  -2.25151107e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -2.97546619283 6.63514400431 
 [[  9.99860051e-01  -9.75599823e-04  -1.67010773e-02   1.33669018e+00]
 [  1.02846985e-03   9.99994487e-01   3.15736978e-03  -7.76866121e-01]
 [  1.66979049e-02  -3.17410446e-03   9.99855542e-01  -2.97546619e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


 10% (115 of 1101) |##                    | Elapsed Time: 0:11:42 ETA:  2:48:33

156 -2.30500333572 [[  9.99987848e-01   4.56871574e-04  -4.90858271e-03   4.52671999e-02]
 [ -4.60114511e-04   9.99999677e-01  -6.59557839e-04   5.00113622e-02]
 [  4.90827979e-03   6.61808334e-04   9.99987735e-01  -2.30500334e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -4.46208035754 3.65509489097 
 [[  9.99944579e-01   4.10740896e-03  -9.69376074e-03   1.25528373e-01]
 [ -4.09596416e-03   9.99990891e-01   1.20019366e-03  -1.53422059e-01]
 [  9.69860212e-03  -1.16042185e-03   9.99952294e-01  -4.46208036e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


 10% (116 of 1101) |##                    | Elapsed Time: 0:11:52 ETA:  2:48:14

318 -2.31759655658 [[  9.99989709e-01   1.01387081e-03  -4.42194782e-03   3.14505938e-02]
 [ -1.01335729e-03   9.99999480e-01   1.18369184e-04   3.51012082e-02]
 [  4.42206553e-03  -1.13886953e-04   9.99990216e-01  -2.31759656e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -3.25513347371 1.66419774178 
 [[ 0.99978519 -0.01063294 -0.01779069  1.23532994]
 [ 0.01075817  0.99991792  0.00695833 -0.75259043]
 [ 0.01771524 -0.00714823  0.99981752 -3.25513347]
 [ 0.          0.          0.          1.        ]]


 10% (117 of 1101) |##                    | Elapsed Time: 0:12:05 ETA:  2:49:46

326 -2.32780922731 [[  9.99992376e-01   1.84617226e-04  -3.90045783e-03   2.17797070e-02]
 [ -1.80446797e-04   9.99999412e-01   1.06954016e-03   1.77352600e-02]
 [  3.90065299e-03  -1.06882818e-03   9.99991821e-01  -2.32780923e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -4.61479654215 0.333528752086 
 [[  9.99975710e-01  -3.42976925e-04  -6.96147193e-03   1.05217210e-02]
 [  3.59894058e-04   9.99996985e-01   2.42900145e-03   3.62954197e-02]
 [  6.96061785e-03  -2.43144784e-03   9.99972819e-01  -4.61479654e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


 10% (118 of 1101) |##                    | Elapsed Time: 0:12:16 ETA:  2:53:31

297 -2.32792425009 [[  9.99991957e-01   1.43807489e-04  -4.00807125e-03   3.08473403e-02]
 [ -1.36577660e-04   9.99998363e-01   1.80403269e-03   1.64381143e-02]
 [  4.00832413e-03  -1.80347077e-03   9.99990340e-01  -2.32792425e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -4.27524502036 -0.553622248639 
 [[  9.99967719e-01   2.30379694e-04  -8.03166850e-03  -5.91669126e-02]
 [ -2.15767221e-04   9.99998320e-01   1.82017606e-03   7.44334985e-02]
 [  8.03207434e-03  -1.81838433e-03   9.99966089e-01  -4.27524502e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


 10% (119 of 1101) |##                    | Elapsed Time: 0:12:30 ETA:  2:58:56

85 -2.32678526262 [[  9.99995547e-01   1.05274271e-03  -2.79259081e-03  -1.12592131e-02]
 [ -1.04920864e-03   9.99998647e-01   1.26667772e-03   3.91781525e-03]
 [  2.79392052e-03  -1.26374207e-03   9.99995298e-01  -2.32678526e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
invalid speed -4.68549423217 -1.14467658663 
 [[  9.99974665e-01  -3.02405616e-04  -7.11177986e-03   2.79025147e-02]
 [  3.17483193e-04   9.99997704e-01   2.11905147e-03  -2.17690682e-03]
 [  7.11112272e-03  -2.12125566e-03   9.99972466e-01  -4.68549423e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


In [ ]:
show2(draw_frame_depth(frame[0]), draw_frame_depth(frame[1]))

Show only the ID's in frame[0] that are actually in frame[1], to avoid clutter in the image.

In [ ]:
#kp0 = [kp for kp in frame[0].get_observations() if kp.get_mappoint() in { p.get_mappoint() for p in frame[1].get_observations() }]
#kp1 = [kp for kp in frame[1].get_observations() if kp.has_mappoint()]
#frame[1].compute_depth()
#show2(draw_observations_depth(kp0), draw_observations_depth(kp1))

In [ ]:
frame[5].compute_depth()
frame[5].filter_not_useful()
frame[6].compute_depth()
frame[6].filter_not_useful()
obs1 = [o for o in frame[5].get_observations() ]
obs2 = [o for o in frame[6].get_observations() ]

In [ ]:
show2(draw_observations_depth(obs1), draw_observations_depth(obs2))

In [ ]:
frame[5].compute_depth()
a = [ (o.get_depth(), o.confidence) for o in frame[5].get_observations() if o.confidence is not None and o.confidence > 1.4 ]
len(a)
#show2(draw_frame(frame[5]), draw_frame(frame[5].get_right_frame()))

In [ ]:
pl = [ o for o in frame[5].get_observations() if o.confidence is not None and o.confidence > 1.4 ]
show(draw_observations_depth(pl))

In [ ]:
show2(draw_frame(frame[0]), draw_frame(f.get_right_frame()))

In [ ]:
f = frame[0]

In [ ]:
f.compute_depth()

In [ ]:
show(draw_observations_depth(frame[0].get_observations()[:100]))